# coding: utf-8

"""
    Aqua Security Test Api Definition Document Authered By - Shaharuk Shaikh

    This document is the api def document api's given to test by Aqua Security  

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.task_id import TaskID  
from openapi_client.rest import ApiException


class TestTaskID(unittest.TestCase):
    """TaskID unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskID(self):
        """Test TaskID"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.task_id.TaskID()  
        pass


if __name__ == '__main__':
    unittest.main()
