# coding: utf-8

"""
    Aqua Security Test Api Definition Document Authered By - Shaharuk Shaikh

    This document is the api def document api's given to test by Aqua Security  

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "openapi-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil", "pytest", "pytest-html"]

setup(
    name=NAME,
    version=VERSION,
    description="Aqua Security Test Api Definition Document Authered By - Shaharuk Shaikh",
    author_email="",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Aqua Security Test Api Definition Document Authered By - Shaharuk Shaikh"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    This document is the api def document api&#39;s given to test by Aqua Security  
    """
)
