# coding: utf-8

"""
    Aqua Security Test Api Definition Document Authered By - Shaharuk Shaikh

    This document is the api def document api's given to test by Aqua Security  

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class TaskDetail(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'task': 'str',
        'completed': 'bool'
    }

    attribute_map = {
        'task': 'task',
        'completed': 'completed'
    }

    def __init__(self, task=None, completed=None):  
        """TaskDetail - a model defined in OpenAPI"""  

        self._task = None
        self._completed = None
        self.discriminator = None

        if task is not None:
            self.task = task
        if completed is not None:
            self.completed = completed

    @property
    def task(self):
        """Gets the task of this TaskDetail.  


        :return: The task of this TaskDetail.  
        :rtype: str
        """
        return self._task

    @task.setter
    def task(self, task):
        """Sets the task of this TaskDetail.


        :param task: The task of this TaskDetail.  
        :type: str
        """

        self._task = task

    @property
    def completed(self):
        """Gets the completed of this TaskDetail.  


        :return: The completed of this TaskDetail.  
        :rtype: bool
        """
        return self._completed

    @completed.setter
    def completed(self, completed):
        """Sets the completed of this TaskDetail.


        :param completed: The completed of this TaskDetail.  
        :type: bool
        """

        self._completed = completed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaskDetail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
